### ISSUE TITLE
reduce chatty-ness of parquet libraries 

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#25]
The chatty nature of parquet libraries cause a deluge of logs (> GB) whenever running a freshdata job. 
Suggest to upgrade to spark > 2.1.1 or add the following to log configuration on worker nodes (also see https://issues.apache.org/jira/browse/SPARK-17993).
```
# attempt to deal with chatty-ness of parquet libs
log4j.logger.org.apache.parquet=ERROR
log4j.logger.parquet=ERROR
```

example of chatty logs : 

```
17/07/05 15:36:18 WARN CorruptStatistics: Ignoring statistics because created_by could not be parsed (see PARQUET-251): parquet-mr version 1.6.0
org.apache.parquet.VersionParser$VersionParseException: Could not parse created_by: parquet-mr version 1.6.0 using format: (.+) version ((.*) )?\(build ?(.*)\)
	at org.apache.parquet.VersionParser.parse(VersionParser.java:112)
	at org.apache.parquet.CorruptStatistics.shouldIgnoreStatistics(CorruptStatistics.java:60)
```

**Comment by mjcollin** [comment]
There was no default log4j.properties for Spark, only a template. That template has been copied to log4j.properties and the above lines are set. Also log4j.rootCategory=WARN, console is set instead of INFO which should cut down on noise too.

Pushed to mesos* nodes.

Please test at your convenience.

**Comment by jhpoelen** [comment]
Look like parquet is a lot less chatty! thanks.
