### ISSUE TITLE
Services are down? - Mesos can't elect a leader

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#32]
At least, existing Fresh Data and Effechecka files are unavailable by API.

**Comment by diatomsRcool** [comment]
I'm having trouble too.

**Comment by godfoder** [comment]
It should currently be running, but I'm attempting to work on the deployment path right now, so it may go down again.

**Comment by mjcollin** [comment]
May or may not be fallout from above but Mesos is having difficulty maintaining a master. The interface will sometimes load and sometimes all nodes will redirect thinking they are not the master.

Output from the iDIgBio_mini_test Jenkins job today shows that it sat for hours waiting for an allocation:
```
I0808 01:39:08.654381  3605 detector.cpp:152] Detected a new leader: (id='73')
I0808 01:39:08.654573  3605 group.cpp:706] Trying to get '/mesos/json.info_0000000073' in ZooKeeper
I0808 01:39:08.655560  3605 zookeeper.cpp:259] A new leading master (UPID=master@10.13.44.18:5050) is detected
I0808 01:39:08.655652  3605 sched.cpp:330] New master detected at master@10.13.44.18:5050
I0808 01:39:08.655841  3605 sched.cpp:341] No credentials provided. Attempting to register without authentication
E0808 01:40:53.391774  3612 process.cpp:2105] Failed to shutdown socket with fd 278: Transport endpoint is not connected
I0808 10:06:06.347523  3605 detector.cpp:152] Detected a new leader: (id='74')
I0808 10:06:06.347683  3611 group.cpp:706] Trying to get '/mesos/json.info_0000000074' in ZooKeeper
I0808 10:06:06.348491  3605 zookeeper.cpp:259] A new leading master (UPID=master@10.13.44.21:5050) is detected
I0808 10:06:06.348570  3605 sched.cpp:330] New master detected at master@10.13.44.21:5050
I0808 10:06:06.348685  3605 sched.cpp:341] No credentials provided. Attempting to register without authentication
I0808 10:06:10.048789  3611 detector.cpp:152] Detected a new leader: (id='76')
I0808 10:06:10.048950  3611 group.cpp:706] Trying to get '/mesos/json.info_0000000076' in ZooKeeper
I0808 10:06:10.050087  3604 zookeeper.cpp:259] A new leading master (UPID=master@10.13.44.24:5050) is detected
I0808 10:06:10.050185  3604 sched.cpp:330] New master detected at master@10.13.44.24:5050
I0808 10:06:10.050297  3604 sched.cpp:341] No credentials provided. Attempting to register without authentication
I0808 10:06:11.901902  3604 sched.cpp:743] Framework registered with d712f8f3-f339-4fbb-a403-936306c0c95f-0001
17/08/08 10:06:11 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41584.
```

Linking in https://github.com/bio-guoda/guoda-datasets/issues/10 since this behavior is the motivation for wanting better job monitoring and alerting.

**Comment by jhammock** [comment]
I don't know if this is relevant, but I may have an updateMonitors job running. I started it last week-
 thursday or friday- and I rather thought it had died, but I see the folder /guoda/data/monitor-test/occurrence  was created yesterday afternoon. If it's running and killing it would be helpful, feel free...

**Comment by jhammock** [comment]
also, I'm not sure if freeing up this amount of space would be helpful, but we might consider deleting /guoda/data/gbif-idigbio.parquet/source=idigbio/d
ate=20161003. There may be something amiss with those data anyway; iDigBio data don't currently show up in any of the FD monitors. There is one more copy to fall back on, from September, which might work better anyway, until we can get an updated copy in there.

**Comment by mjcollin** [comment]
Restarting the services doesn't help. The last status from `service mesos-master status` on all hosts is

```
Aug 11 16:26:42 mesos03 mesos-master[26485]: E0811 16:26:42.040518 26502 process.cpp:2105] Failed to shutdown socket with fd 1425: Transport endpoint is not connected
```

Looking for that message yields this post https://stackoverflow.com/questions/31858937/transport-endpoint-not-connected-mesos-slave-master which describes the circular election behavior we're having.

Command used to start Mesos (from the service status):

```
/usr/sbin/mesos-master --zk=zk://mesos02:2181,mesos01:2181,mesos03:2181/mesos --port=5050 --log_dir=/var/log/mesos --quorum=1 --work_dir=/var/lib/mesos
```

so we are saying quorum=1 with for 3 nodes would yeild circular elections. /etc/mesos-master/quorum has "1" in it and is last mode 8/26/2016.

Changed quorum and that seemed to help stabalize things. But this is in the logs on mesos01:

```
I0811 16:36:14.196740 27086 master.cpp:1847] The newly elected leader is master@10.13.44.48:5050 with id 90c501d7-1666-4b40-ad52-2b402a71d2e3
```

That IP address is mesos12. Turns out _ALL_ the nodes are running the mesos-master service. Quorum=2 isn't enough for that. mesos.master state is not applied to these nodes, I think someone manually applied that state by accident and my bash history doesn't have that command. @godfoder ?

Stopped mesos-master and zookeeper on 04-12. Restarted all services throughout cluster.

Verified manual pyspark connection makes a framework, Jupyter notebook kernels work, Jenkins iDigBio_mini_test works. Have not yet verified FD gives me a checklist.

Much sanity has returned.

**Comment by mjcollin** [comment]
FD jobs work although I left the page up for the ~16 minutes it took to run and there was no little progress bar and the page did not reload. I manually reloaded the page and I got my occurrences after the framework finished:

http://gimmefreshdata.github.io/?limit=20&taxonSelector=Acer&traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29%2CPOLYGON%20%28%28-82.64465332031249%2029.29598055871569%2C%20-82.21618652343749%2030.0405664305846%2C%20-81.9085693359375%2029.783449456820605%2C%20-82.0733642578125%2029.267232865200878%2C%20-82.64465332031249%2029.29598055871569%29%29%29

**Comment by jhammock** [comment]
That is expected behavior- the leaner meaner FD doesn't have progress indicators. It's aliiiiiive!

**Comment by mjcollin** [comment]
Disabled mesos-master and zookeeper on 04-12. Added /etc/mesos-master/quorum to files managed by Salt.
