### ISSUE TITLE
no cluster capacity?

### ISSUE THREAD

**Issue by jhammock** [bio-guoda/guoda-services#42]
I've been trying a makeparquet job for a few days now and been declined each time. Is the cluster choking on something?

**Comment by jhpoelen** [comment]
As far as I can tell, the cluster is eagerly munching on checklists (see attached screenshot). Due to a lack of queuing mechanism (see #28), your jobs just get rejected unless none is running. Since http://archive.guoda.bio/job/ecoregion%20status%20checker/ is pretty successful attempting at scheduling jobs, you probably ended up getting the short and of the stick. As far as the checklists go - 324 calculated, 7700 to go.

Bottomline - a queuing mechanism would be nice to have. Meanwhile, as a workaround, you can ask @diatomsRcool to temporarily pause the job (or do it yourself), wait for about 10-20 minutes or so, then run the parquet conversion before then resume the checklist job.

![screenshot from 2018-01-22 10-21-40](https://user-images.githubusercontent.com/1084872/35237051-48b8a300-ff5e-11e7-9774-79b1e479df69.png)

**Comment by jhammock** [comment]
Good to know, thanks. I'll coordinate with @diatomsRcool 

#wishIcouldseethoselogs

**Comment by jhpoelen** [comment]
I get logs through ssh account I got via @mjcollin using socks tunnel (see https://www.digitalocean.com/community/tutorials/how-to-route-web-traffic-securely-without-a-vpn-using-a-socks-tunnel) . 

An alternate method is to start a terminal in jupyter and then run 

```curl http://mesos02.acis.ufl.edu:5050/tasks | python -m json.tool | more```

This gives you a paged list of tasks (running and finished). Press space bar to scroll down.

Maybe @godfoder or @mjcollin have some other ideas to help you peek into the cluster.

**Comment by jhammock** [comment]
Oh, nice. Peeking in jupyter works nicely for my occasional needs, thanks!
