### ISSUE TITLE
effechecka doesn't work because it can't connect to HDFS

### ISSUE THREAD

**Issue by jhpoelen** [bio-guoda/guoda-services#44]
From a quick glance at the effechecka logs, it appears that connections to HDFS cannot be made. Without HDFS effechecka (and freshdata) cannot function properly.

@godfoder @mjcollin any idea why this is happening? Is it related to https://github.com/bio-guoda/guoda-services/issues/40 ?

```
18-01-29 16:11:38 WARN RetryInvocationHandler: Exception while invoking class org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo over mesos02.acis.ufl.edu/10.13.44.18:8020. Not retrying because failovers (15) exceeded maximum allowed (15)
java.net.ConnectException: Call From 0e4a88aef704/172.17.0.2 to mesos02.acis.ufl.edu:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
```

**Comment by mjcollin** [comment]
It looks like the primary name node on mesos02 wasn't running. I restarted the machine since that's an easy way to restart the services in the correct order and it wasn't running any jobs. While loading edit files, the name node process ran out of memory. I'll up the memory and try again. Later today I'll know if that worked.

This is indicative of the HDFS file system going too long without a checkpoint. I'll look at that configuration setting when it's been successfully started once. In the mean time, it may take 6 or more hours to restart HDFS and I'll need to do that once or twice to fix it.

**Comment by jhpoelen** [comment]
@mjcollin Thanks for having a look and poking around. If I understand it correctly, the primary name node crashed somehow and needs to rebuild hdfs indexes. Curious to hear why some other name node didn't assume the role of the primary name node.

**Comment by mjcollin** [comment]
Today's update, figured out how to increase namenode memory, starting again, it appears it got half-way done loading logs last time in about 2 hours so I'll check it this evening to see if it finished. Then I'll make sure the file system gets checkpointed and restart it to make sure it has committed all the logs. At that point it should be up and I'll look at the HA issue because yes, it should have failed over.

**Comment by mjcollin** [comment]
Just had a minute to check on progress and the namenode is back up. I'll be doing investigation and restarts to confirm it's working in the next few days.

**Comment by jhpoelen** [comment]
@mjcollin great! Looks like data is flowing again . . . related to https://github.com/jhpoelen/effechecka/issues/81 .

![screenshot from 2018-01-31 11-44-35](https://user-images.githubusercontent.com/1084872/35643823-45cb6a54-067c-11e8-96c5-e3a368b53f30.png)

**Comment by turnerh** [comment]
Have been running searches succesfully already! Thanks for solving this.

**Comment by mjcollin** [comment]
(2) things lead to this: the FS wasn't being chckpointed hence the long time to replay logs and second the secondary name node says it's name node storage has failed (it's a folder on disk with permissions it can write to).

I'll be making sure the one working name node is properly checkpointed and restarting HDFS on it to confirm that. Then I'm going to work on a separate task of setting up the HDFS->NFS gateway so I can add the cluster to our normal backup rotation before getting too wild with formatting name nodes, the recommended fix for out of sync nodes.

HDFS may go down and come back up this evening.

Edit: Well here's why it's not checkpointing: "So, rather than pausing the active NameNode to perform a checkpoint, HDFS defers it to either the SecondaryNameNode or Standby NameNode"

Edit2: Plan

1. Backup /srv/hdfs_data/hdfs/nn/ on primary and secondary
1. Stop HDFS on secondary
1. clear out nn dir on secondary
1. hdfs secondarynamenode -checkpoint force to see if this copies over the nn data from primary -> "Cannot use SecondaryNameNode in an HA cluster. The Standby Namenode will perform checkpointing."
1. if it does, start HDFS on secondary
1. watch to see if it checkpoints on it's own 

Ref: https://books.google.com/books?id=hnc5DwAAQBAJ&pg=PA132&lpg=PA132&dq=hdfs+primary+checkpoint&source=bl&ots=q3OQ1smaaH&sig=2fb9_t_5UKt1_JKIhhtCVVB7E-4&hl=en&sa=X&ved=0ahUKEwiM9_yH4o_ZAhUFx1kKHRXgBbwQ6AEIOzAD#v=onepage&q=hdfs%20primary%20checkpoint&f=false

**Comment by mjcollin** [comment]
Ended up simply restarting secondary name node service. Currently replaying edits that it has, see if when it's done it starts picking up edits from primary.

Journal node service is also down on this node which is what provides the sync mechanism, will restart when namenode service is finished.

**Comment by mjcollin** [comment]
Secondary didn't replay correctly. Need to schedule downtime #45

**Comment by mjcollin** [comment]
Please re-test, I believe HDFS is happy now.

**Comment by jhpoelen** [comment]
@mjcollin Thanks!
